# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image/%Y/%m/'),
        ),
    ]
